# Generated by Django 4.0.3 on 2023-05-26 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=255, verbose_name='Rua')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='core.cidade', verbose_name='Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('cargo', models.CharField(max_length=255, verbose_name='Cargo')),
                ('enderecos', models.ManyToManyField(related_name='funcionarios', to='core.endereco', verbose_name='Enderecos')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.PositiveSmallIntegerField(verbose_name='Quantidade')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateField(verbose_name='Data Pedido')),
                ('quantidade', models.PositiveSmallIntegerField(verbose_name='Quantidade')),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preco Total')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='core.cliente', verbose_name='Cliente')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='core.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('cnpj', models.CharField(max_length=20, verbose_name='Nome')),
                ('enderecos', models.ManyToManyField(related_name='fornecedores', to='core.endereco', verbose_name='Enderecos')),
                ('produtos', models.ManyToManyField(related_name='fornecedor', to='core.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField(verbose_name='Data Pedido')),
                ('quantidade', models.PositiveSmallIntegerField(verbose_name='Quantidade')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='core.fornecedor')),
                ('produtos', models.ManyToManyField(related_name='compras', to='core.produto')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='enderecos',
            field=models.ManyToManyField(related_name='clientes', to='core.endereco', verbose_name='Enderecos'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='core.pais', verbose_name='Pais'),
        ),
    ]
