# Generated by Django 4.0.3 on 2023-05-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto_descricao_alter_pais_nome_alter_produto_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
    ]
